---
version: "3.7"
services:
  front-envoy:
    build: .
    networks:
      - envoymesh
    volumes:
      - ./envoy.yaml:/etc/front-envoy.yaml
    logging:
      driver: none
    ports:
      # Http Access port
      - "8080:8080"
      # Https Access port (not implemented)
      - "8443:8443"
      # Envoy admin
      - "8001:8001"

  auth:
    image: zwiter/auth:1.0
    networks:
      - envoymesh
    environment:
      GODEBUG: x509ignoreCN=0
      SERVICE_NAME: auth
    volumes:
      - ./auth/config:/config
      - ./auth/bin:/zwitter-bin
      - ./auth/swagger:/swagger
    expose:
      # Http server runs on this port with envoy
      - "8000"
      # gRPC server runs on this port
      - "9999"

  posts:
    image: zwiter/posts:1.0
    networks:
      - envoymesh
    environment:
      GODEBUG: x509ignoreCN=0
      SERVICE_NAME: posts
    volumes:
      - ./posts/config:/config
      - ./posts/bin:/zwitter-bin
      - ./posts/swagger:/swagger
    expose:
      # Http server runs on this port with envoy
      - "8000"
      # gRPC server runs on this port
      - "7777"

  users:
    image: zwiter/users:1.0
    networks:
      - envoymesh
    environment:
      GODEBUG: x509ignoreCN=0
      SERVICE_NAME: users
    volumes:
      - ./users/config:/config
      - ./users/bin:/zwitter-bin
      - ./users/swagger:/swagger
    expose:
      # gRPC server runs on this port
      - "8000"
      # gRPC server runs on this port
      - "8888"

networks:
  envoymesh: {}
