ServiceConfig:
  Server:
    Name: Web
    RestAddr: 0.0.0.0:5556
    CertFile: cert/server.crt
    KeyFile: cert/server.key
    ServerName: zwitter
    Nodes:
      - Name: Auth
        Host: auth
        Port: 9999
      - Name: Posts
        Host: posts
        Port: 7777
      - Name: Users
        Host: users
        Port: 8888
AssetsPath: /dist

